FROM node:22-alpine AS build

WORKDIR /app

COPY apps/mission-control/package*.json ./
RUN npm ci

COPY apps/mission-control/ ./
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27-alpine

ARG VCS_REF=unknown
ARG BUILD_DATE=unknown

LABEL org.opencontainers.image.source="https://github.com/martinp09/Ares" \
    org.opencontainers.image.revision="$VCS_REF" \
    org.opencontainers.image.created="$BUILD_DATE" \
    org.opencontainers.image.title="Ares Mission Control UI"

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080
