import type { MissionControlSnapshot, TasksData } from "./api";

export const missionControlTasksFixture: TasksData = {
  dueCount: 2,
  tasks: [
    {
      threadId: "mc-thread-lease-option-1",
      leadName: "Jordan Pending",
      channel: "sms",
      bookingStatus: "pending",
      sequenceStatus: "active",
      nextSequenceStep: "manual_call_day_3",
      manualCallDueAt: "2026-04-16T22:30:00+00:00",
      recentReplyPreview: "If this works I can jump on a call tonight.",
      replyNeedsReview: true,
    },
    {
      threadId: "mc-thread-lease-option-2",
      leadName: "Morgan Callback",
      channel: "call",
      bookingStatus: "pending",
      sequenceStatus: "paused",
      nextSequenceStep: "manual_call_followup",
      manualCallDueAt: "2026-04-16T23:15:00+00:00",
      recentReplyPreview: null,
      replyNeedsReview: false,
    },
  ],
};

export const missionControlFixtures: MissionControlSnapshot = {
  dashboard: {
    approvalCount: 4,
    activeRunCount: 6,
    failedRunCount: 1,
    activeAgentCount: 2,
    unreadConversationCount: 8,
    busyChannelCount: 2,
    recentCompletedCount: 14,
    pendingLeadCount: 7,
    bookedLeadCount: 4,
    activeNonBookerEnrollmentCount: 5,
    dueManualCallCount: 2,
    repliesNeedingReviewCount: 3,
    outboundProbateSummary: {
      activeCampaignCount: 6,
      readyLeadCount: 7,
      activeLeadCount: 5,
      interestedLeadCount: 3,
      suppressedLeadCount: 2,
      openTaskCount: 2,
    },
    inboundLeaseOptionSummary: {
      pendingLeadCount: 7,
      bookedLeadCount: 4,
      activeNonBookerEnrollmentCount: 5,
      dueManualCallCount: 2,
      repliesNeedingReviewCount: 3,
    },
    opportunityCount: 6,
    opportunityStageSummaries: [
      { sourceLane: "probate", stage: "qualified_opportunity", count: 2 },
      { sourceLane: "probate", stage: "contract_sent", count: 1 },
      { sourceLane: "lease_option_inbound", stage: "qualified_opportunity", count: 1 },
      { sourceLane: "lease_option_inbound", stage: "contract_sent", count: 1 },
      { sourceLane: "lease_option_inbound", stage: "title_open", count: 1 },
    ],
    opportunityPipelineSummary: {
      totalOpportunityCount: 6,
      laneStageSummaries: [
        { sourceLane: "probate", stage: "qualified_opportunity", count: 2 },
        { sourceLane: "probate", stage: "contract_sent", count: 1 },
        { sourceLane: "lease_option_inbound", stage: "qualified_opportunity", count: 1 },
        { sourceLane: "lease_option_inbound", stage: "contract_sent", count: 1 },
        { sourceLane: "lease_option_inbound", stage: "title_open", count: 1 },
      ],
    },
    systemStatus: "healthy",
    updatedAt: "Updated 2 minutes ago",
  },
  inbox: {
    selectedConversationId: "conv-1001",
    conversations: [
      {
        id: "conv-1001",
        leadName: "Taylor Brooks",
        channel: "SMS",
        stage: "Warm lead",
        owner: "Sierra",
        unreadCount: 2,
        lastMessage: "Can you send over the numbers for Oak Street?",
        lastActivityAt: "2m ago",
        sequenceState: "Manual review",
      },
      {
        id: "conv-1002",
        leadName: "Jordan Patel",
        channel: "Call",
        stage: "Follow-up",
        owner: "Atlas",
        unreadCount: 0,
        lastMessage: "Left voicemail with pricing summary.",
        lastActivityAt: "18m ago",
        sequenceState: "Nurture day 3",
      },
      {
        id: "conv-1003",
        leadName: "Morgan Lee",
        channel: "Email",
        stage: "New inquiry",
        owner: "Hermes",
        unreadCount: 1,
        lastMessage: "Interested in the Riverside package details.",
        lastActivityAt: "41m ago",
        sequenceState: "Unassigned",
      },
    ],
    threadsById: {
      "conv-1001": {
        conversationId: "conv-1001",
        leadName: "Taylor Brooks",
        company: "Oak Street Holdings",
        stage: "Warm lead",
        nextBestAction: "Approve the pricing reply draft and launch research follow-up.",
        tags: ["seller", "pricing", "priority"],
        notes: [
          "Asked for comparative numbers twice today.",
          "Prefers SMS over voice unless a contract is ready.",
        ],
        messages: [
          {
            id: "msg-1",
            author: "Taylor Brooks",
            direction: "inbound",
            body: "Can you send over the numbers for Oak Street?",
            timestamp: "7:08 PM",
            status: "received",
          },
          {
            id: "msg-2",
            author: "Hermes draft",
            direction: "outbound",
            body: "I have the latest comp set ready. Do you want the short summary or full packet?",
            timestamp: "7:10 PM",
            status: "awaiting approval",
          },
          {
            id: "msg-3",
            author: "Operator note",
            direction: "internal",
            body: "If approved, trigger market research refresh before sending packet.",
            timestamp: "7:11 PM",
            status: "logged",
          },
        ],
      },
      "conv-1002": {
        conversationId: "conv-1002",
        leadName: "Jordan Patel",
        company: "Crescent Homes",
        stage: "Follow-up",
        nextBestAction: "Schedule a retry call window for tomorrow morning.",
        tags: ["voicemail", "callback"],
        notes: ["Voicemail referenced prior conversation from last week."],
        messages: [
          {
            id: "msg-4",
            author: "Atlas",
            direction: "outbound",
            body: "Called and left voicemail with pricing summary.",
            timestamp: "6:54 PM",
            status: "completed",
          },
        ],
      },
      "conv-1003": {
        conversationId: "conv-1003",
        leadName: "Morgan Lee",
        company: "Riverside Equity",
        stage: "New inquiry",
        nextBestAction: "Assign to inbox queue and draft qualification questions.",
        tags: ["email", "new"],
        notes: ["Inbound email came from the website contact form."],
        messages: [
          {
            id: "msg-5",
            author: "Morgan Lee",
            direction: "inbound",
            body: "Interested in the Riverside package details.",
            timestamp: "6:29 PM",
            status: "received",
          },
        ],
      },
    },
  },
  tasks: missionControlTasksFixture,
  approvals: [
    {
      id: "apr-1001",
      title: "Approve pricing follow-up reply",
      reason: "Customer-facing message triggered always_ask policy.",
      riskLevel: "medium",
      status: "pending",
      commandType: "send_sms_reply",
      requestedAt: "2m ago",
      payloadPreview: "Send comp summary and ask whether to deliver the short or full packet.",
    },
    {
      id: "apr-1002",
      title: "Approve outbound call retry",
      reason: "Voice outreach is gated for this agent revision.",
      riskLevel: "high",
      status: "pending",
      commandType: "launch_call",
      requestedAt: "18m ago",
      payloadPreview: "Retry call with Jordan Patel tomorrow at 9:30 AM.",
    },
  ],
  runs: [
    {
      id: "run-1001",
      commandType: "run_market_research",
      status: "in_progress",
      businessId: "limitless",
      environment: "dev",
      updatedAt: "1m ago",
      parentRunId: null,
      triggerRunId: "trg-7711",
      summary: "Refreshing Oak Street market comps for the approval thread.",
      replay: {
        role: "parent",
        requestedAt: "2026-04-16T21:58:00+00:00",
        resolvedAt: "2026-04-16T21:58:00+00:00",
        replayReason: "Refresh Oak Street under the rolled-back release.",
        requiresApproval: false,
        childRunId: "run-1002",
        triggeringActor: {
          orgId: "org_internal",
          actorId: "ops-42",
          actorType: "user",
        },
        source: {
          agentId: "agt-1001",
          agentRevisionId: "rev-198",
          activeRevisionId: "rev-198",
          revisionState: "published",
          releaseChannel: "dogfood",
          releaseEventId: "rle-9001",
          releaseEventType: "publish",
        },
        replay: {
          agentId: "agt-1001",
          agentRevisionId: "rev-198",
          activeRevisionId: "rev-201",
          revisionState: "published",
          releaseChannel: "dogfood",
          releaseEventId: "rle-9003",
          releaseEventType: "rollback",
        },
      },
    },
    {
      id: "run-1002",
      commandType: "assemble_launch_proposal",
      status: "completed",
      businessId: "limitless",
      environment: "dev",
      updatedAt: "16m ago",
      parentRunId: "run-1001",
      triggerRunId: "trg-7712",
      summary: "Child run attached the draft proposal artifact bundle.",
      replay: {
        role: "child",
        requestedAt: "2026-04-16T21:58:00+00:00",
        resolvedAt: "2026-04-16T21:58:00+00:00",
        replayReason: "Refresh Oak Street under the rolled-back release.",
        childRunId: "run-1002",
        parentRunId: "run-1001",
        triggeringActor: {
          orgId: "org_internal",
          actorId: "ops-42",
          actorType: "user",
        },
        source: {
          agentId: "agt-1001",
          agentRevisionId: "rev-198",
          activeRevisionId: "rev-198",
          revisionState: "published",
          releaseChannel: "dogfood",
          releaseEventId: "rle-9001",
          releaseEventType: "publish",
        },
        replay: {
          agentId: "agt-1001",
          agentRevisionId: "rev-198",
          activeRevisionId: "rev-201",
          revisionState: "published",
          releaseChannel: "dogfood",
          releaseEventId: "rle-9003",
          releaseEventType: "rollback",
        },
      },
    },
    {
      id: "run-1003",
      commandType: "launch_call",
      status: "failed",
      businessId: "limitless",
      environment: "dev",
      updatedAt: "22m ago",
      parentRunId: null,
      triggerRunId: "trg-7713",
      summary: "Provider timeout before the call workflow could confirm routing.",
    },
  ],
  turns: [
    {
      id: "trn-1001",
      sessionId: "ses-1001",
      businessId: "limitless",
      environment: "dev",
      agentId: "agt-1001",
      agentRevisionId: "rev-201",
      turnNumber: 1,
      state: "completed",
      retryCount: 0,
      resumedFromTurnId: null,
      updatedAt: "3m ago",
    },
    {
      id: "trn-1002",
      sessionId: "ses-1002",
      businessId: "limitless",
      environment: "dev",
      agentId: "agt-1002",
      agentRevisionId: "rev-202",
      turnNumber: 2,
      state: "waiting_for_tool",
      retryCount: 1,
      resumedFromTurnId: "trn-1000",
      updatedAt: "11m ago",
    },
  ],
  agents: [
    {
      id: "agt-1001",
      name: "Sierra Inbox Agent",
      activeRevisionId: "rev-201",
      activeRevisionState: "published",
      environment: "production",
      liveSessionCount: 2,
      delegatedWorkCount: 4,
      release: {
        eventId: "rle-9003",
        eventType: "rollback",
        releaseChannel: "dogfood",
        createdAt: "2026-04-16T21:57:00+00:00",
        previousActiveRevisionId: "rev-205",
        targetRevisionId: "rev-198",
        resultingActiveRevisionId: "rev-201",
        rollbackSourceRevisionId: "rev-198",
        evaluation: {
          outcomeId: "out-9002",
          outcomeName: "rollback_assessment",
          status: "failed",
          satisfied: false,
          evaluatorResult: "Regression confirmed in production.",
          failureDetails: ["Latest promotion regressed reply quality."],
          rubricCriteria: ["known good revision exists", "operator confirmed regression"],
          requirePassingEvaluation: false,
          blockedPromotion: false,
          rollbackReason: "Operator reported a production regression after promotion",
        },
      },
    },
    {
      id: "agt-1002",
      name: "Atlas Research Agent",
      activeRevisionId: "rev-202",
      activeRevisionState: "draft",
      environment: "staging",
      liveSessionCount: 1,
      delegatedWorkCount: 2,
    },
  ],
  assets: [
    {
      id: "asset-1001",
      name: "Twilio voice line",
      category: "telephony",
      status: "connected",
      bindingTarget: "production",
      updatedAt: "1h ago",
    },
    {
      id: "asset-1002",
      name: "Vapi assistant",
      category: "voice",
      status: "attention",
      bindingTarget: "staging",
      updatedAt: "3h ago",
    },
    {
      id: "asset-1003",
      name: "SMTP relay",
      category: "email",
      status: "unbound",
      bindingTarget: "not set",
      updatedAt: "Never",
    },
  ],
  governance: {
    orgId: "org_internal",
    pendingApprovals: [
      {
        id: "apr-governance-1",
        title: "Approve outbound policy update",
        reason: "Campaign launch stays operator-gated.",
        riskLevel: "medium",
        status: "pending",
        commandType: "publish_campaign",
        requestedAt: "5m ago",
        payloadPreview: "Publish the latest outbound configuration.",
      },
    ],
    secretsHealth: {
      activeRevisionCount: 2,
      healthyRevisionCount: 1,
      attentionRevisionCount: 1,
      requiredSecretCount: 3,
      configuredSecretCount: 2,
      missingSecretCount: 1,
      revisions: [
        {
          agentId: "agt-1001",
          agentName: "Sierra Inbox Agent",
          agentRevisionId: "rev-201",
          businessId: "limitless",
          environment: "production",
          status: "healthy",
          requiredSecretCount: 2,
          configuredSecretCount: 2,
          missingSecretCount: 0,
          requiredSecrets: ["textgrid_auth_token", "resend_api_key"],
          configuredSecrets: ["textgrid_auth_token", "resend_api_key"],
          missingSecrets: [],
        },
        {
          agentId: "agt-1002",
          agentName: "Atlas Research Agent",
          agentRevisionId: "rev-202",
          businessId: "limitless",
          environment: "staging",
          status: "attention",
          requiredSecretCount: 1,
          configuredSecretCount: 0,
          missingSecretCount: 1,
          requiredSecrets: ["provider_api_key"],
          configuredSecrets: [],
          missingSecrets: ["provider_api_key"],
        },
      ],
    },
    recentAudit: [
      {
        id: "audit-1001",
        eventType: "secret_accessed",
        summary: "Operator viewed Sierra secret posture.",
        resourceType: "secret",
        resourceId: "sec-1001",
        createdAt: "2026-04-16T22:08:00+00:00",
      },
      {
        id: "audit-1002",
        eventType: "approval_requested",
        summary: "Campaign publish requires operator approval.",
        resourceType: "approval",
        resourceId: "apr-governance-1",
        createdAt: "2026-04-16T22:04:00+00:00",
      },
    ],
    usageSummary: {
      totalCount: 9,
      byKind: {
        tool_call: 5,
        host_dispatch: 4,
      },
      bySourceKind: [
        {
          key: "hermes",
          label: "hermes",
          count: 5,
          lastUsedAt: "2026-04-16T22:08:00+00:00",
        },
      ],
      byAgent: [
        {
          key: "agt-1001",
          label: "agt-1001",
          count: 6,
          lastUsedAt: "2026-04-16T22:08:00+00:00",
        },
      ],
      updatedAt: "2026-04-16T22:08:00+00:00",
    },
    recentUsage: [
      {
        id: "usage-1001",
        kind: "tool_call",
        count: 3,
        sourceKind: "hermes",
        createdAt: "2026-04-16T22:08:00+00:00",
      },
      {
        id: "usage-1002",
        kind: "host_dispatch",
        count: 2,
        sourceKind: "trigger_dev",
        createdAt: "2026-04-16T22:03:00+00:00",
      },
    ],
  },
};
