begin;

create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  source_lane text not null,
  strategy_lane text,
  stage text not null default 'qualified_opportunity',
  lead_id bigint,
  contact_id bigint,
  title_status text not null default 'not_open',
  tc_status text not null default 'not_started',
  dispo_status text not null default 'not_ready',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint opportunities_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint opportunities_lead_tenant_fkey
    foreign key (lead_id, business_id, environment)
    references public.leads (id, business_id, environment)
    on delete set null,
  constraint opportunities_contact_tenant_fkey
    foreign key (contact_id, business_id, environment)
    references public.contacts (id, business_id, environment)
    on delete set null,
  constraint opportunities_source_lane_check
    check (source_lane in ('probate', 'lease_option_inbound')),
  constraint opportunities_stage_check
    check (
      stage in (
        'qualified_opportunity',
        'offer_path_selected',
        'under_negotiation',
        'contract_sent',
        'contract_signed',
        'title_open',
        'curative_review',
        'dispo_ready',
        'closed',
        'dead'
      )
    ),
  constraint opportunities_title_status_check
    check (title_status in ('not_open', 'open', 'curative_review', 'cleared', 'blocked')),
  constraint opportunities_tc_status_check
    check (tc_status in ('not_started', 'active', 'waiting', 'complete', 'blocked')),
  constraint opportunities_dispo_status_check
    check (dispo_status in ('not_ready', 'ready', 'marketing', 'assigned', 'complete', 'blocked')),
  constraint opportunities_identity_check
    check (num_nonnulls(lead_id, contact_id) = 1)
);

create unique index if not exists opportunities_tenant_id_unique_idx
  on public.opportunities (id, business_id, environment);
create unique index if not exists opportunities_lead_unique_idx
  on public.opportunities (business_id, environment, lead_id)
  where lead_id is not null;
create unique index if not exists opportunities_contact_unique_idx
  on public.opportunities (business_id, environment, contact_id)
  where contact_id is not null;
create index if not exists opportunities_stage_idx
  on public.opportunities (business_id, environment, stage, updated_at desc);
create index if not exists opportunities_lane_idx
  on public.opportunities (business_id, environment, source_lane, updated_at desc);

drop trigger if exists opportunities_touch_updated_at on public.opportunities;
create trigger opportunities_touch_updated_at
before update on public.opportunities
for each row execute function public.touch_updated_at();

alter table public.opportunities enable row level security;

create policy opportunities_tenant_isolation on public.opportunities
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

commit;
