create table if not exists public.opportunity_pipeline_configs (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  source_lane text not null,
  name text not null,
  stages jsonb not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint opportunity_pipeline_configs_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint opportunity_pipeline_configs_scope_lane_unique
    unique (business_id, environment, source_lane),
  constraint opportunity_pipeline_configs_source_lane_check
    check (source_lane in ('probate', 'lease_option_inbound')),
  constraint opportunity_pipeline_configs_stages_check
    check (jsonb_typeof(stages) = 'array' and jsonb_array_length(stages) > 0)
);

create table if not exists public.opportunity_stage_history (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  opportunity_id bigint not null,
  from_stage text,
  to_stage text not null,
  actor_id text,
  actor_type text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint opportunity_stage_history_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint opportunity_stage_history_opportunity_fkey
    foreign key (opportunity_id, business_id, environment)
    references public.opportunities (id, business_id, environment)
    on delete cascade,
  constraint opportunity_stage_history_from_stage_check
    check (from_stage is null or from_stage in ('qualified_opportunity', 'offer_path_selected', 'under_negotiation', 'contract_sent', 'contract_signed', 'title_open', 'curative_review', 'dispo_ready', 'closed', 'dead')),
  constraint opportunity_stage_history_to_stage_check
    check (to_stage in ('qualified_opportunity', 'offer_path_selected', 'under_negotiation', 'contract_sent', 'contract_signed', 'title_open', 'curative_review', 'dispo_ready', 'closed', 'dead'))
);

create index if not exists opportunity_stage_history_opportunity_idx
  on public.opportunity_stage_history (business_id, environment, opportunity_id, created_at desc);

alter table public.opportunity_pipeline_configs enable row level security;
alter table public.opportunity_stage_history enable row level security;

drop policy if exists opportunity_pipeline_configs_tenant_isolation on public.opportunity_pipeline_configs;
create policy opportunity_pipeline_configs_tenant_isolation on public.opportunity_pipeline_configs
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop policy if exists opportunity_stage_history_tenant_isolation on public.opportunity_stage_history;
create policy opportunity_stage_history_tenant_isolation on public.opportunity_stage_history
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop trigger if exists opportunity_pipeline_configs_touch_updated_at on public.opportunity_pipeline_configs;
create trigger opportunity_pipeline_configs_touch_updated_at
before update on public.opportunity_pipeline_configs
for each row execute function public.touch_updated_at();
