-- Additive managed-agent persistence tables for Supabase-backed repositories.
-- Scope intentionally limited to permissions, outcomes, and operational assets.

begin;

create table if not exists public.agent_tool_permissions (
  id bigint generated by default as identity primary key,
  runtime_id text not null,
  agent_revision_id text not null,
  tool_name text not null,
  mode text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_tool_permissions_runtime_id_unique unique (runtime_id),
  constraint agent_tool_permissions_revision_tool_unique unique (agent_revision_id, tool_name),
  constraint agent_tool_permissions_mode_check
    check (mode in ('always_allow', 'always_ask', 'forbidden'))
);

create index if not exists agent_tool_permissions_revision_idx
  on public.agent_tool_permissions (agent_revision_id);
create index if not exists agent_tool_permissions_tool_idx
  on public.agent_tool_permissions (tool_name);

create table if not exists public.outcome_evaluations (
  id bigint generated by default as identity primary key,
  runtime_id text not null,
  outcome_name text not null,
  artifact_type text not null,
  artifact_payload jsonb not null default '{}'::jsonb,
  rubric_criteria jsonb not null default '[]'::jsonb,
  evaluator_result text not null,
  status text not null,
  satisfied boolean not null default false,
  failure_details jsonb not null default '[]'::jsonb,
  run_runtime_id text,
  created_at timestamptz not null default now(),
  constraint outcome_evaluations_runtime_id_unique unique (runtime_id),
  constraint outcome_evaluations_status_check
    check (status in ('satisfied', 'failed'))
);

create index if not exists outcome_evaluations_run_runtime_id_idx
  on public.outcome_evaluations (run_runtime_id);
create index if not exists outcome_evaluations_created_at_idx
  on public.outcome_evaluations (created_at desc);

create table if not exists public.agent_operational_assets (
  id bigint generated by default as identity primary key,
  runtime_id text not null,
  agent_id text not null,
  business_id text not null,
  environment text not null,
  asset_type text not null,
  label text not null,
  connect_later boolean not null default true,
  status text not null,
  metadata jsonb not null default '{}'::jsonb,
  binding_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  bound_at timestamptz,
  constraint agent_operational_assets_runtime_id_unique unique (runtime_id),
  constraint agent_operational_assets_status_check
    check (status in ('unbound', 'bound')),
  constraint agent_operational_assets_type_check
    check (asset_type in ('calendar', 'form', 'phone_number', 'inbox', 'webhook'))
);

create index if not exists agent_operational_assets_agent_id_idx
  on public.agent_operational_assets (agent_id);
create index if not exists agent_operational_assets_business_env_idx
  on public.agent_operational_assets (business_id, environment);
create index if not exists agent_operational_assets_updated_at_idx
  on public.agent_operational_assets (updated_at desc);

commit;
