begin;

create table if not exists public.title_packets (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  identity_key text not null,
  external_key text not null,
  lead_id bigint,
  status text not null default 'imported',
  priority text not null default 'normal',
  owner_name text,
  estate_name text,
  property_address text,
  mailing_address text,
  probate_case_number text,
  hctax_account text,
  packet_source text,
  operator_lane text,
  assigned_to text,
  artifact_refs jsonb not null default '[]'::jsonb,
  review_notes text,
  facts jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint title_packets_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint title_packets_tenant_id_unique
    unique (id, business_id, environment),
  constraint title_packets_lead_tenant_fkey
    foreign key (lead_id, business_id, environment)
    references public.leads (id, business_id, environment)
    on delete set null,
  constraint title_packets_scope_identity_unique
    unique (business_id, environment, identity_key),
  constraint title_packets_status_check
    check (status in ('imported', 'needs_review', 'in_review', 'completed', 'blocked')),
  constraint title_packets_priority_check
    check (priority in ('normal', 'high', 'urgent'))
);

create index if not exists title_packets_scope_lead_idx
  on public.title_packets (business_id, environment, lead_id, created_at desc);

create index if not exists title_packets_scope_status_idx
  on public.title_packets (business_id, environment, status, priority, created_at desc);

drop trigger if exists title_packets_touch_updated_at on public.title_packets;
create trigger title_packets_touch_updated_at
before update on public.title_packets
for each row execute function public.touch_updated_at();

alter table public.title_packets enable row level security;

create policy title_packets_tenant_isolation on public.title_packets
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

commit;
