begin;

create table if not exists public.crm_source_records (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  identity_key text not null,
  source_system text not null,
  source_key text not null,
  source_type text,
  payload jsonb not null default '{}'::jsonb,
  extracted_at timestamptz,
  confidence numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_source_records_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint crm_source_records_tenant_id_unique
    unique (id, business_id, environment),
  constraint crm_source_records_scope_identity_unique
    unique (business_id, environment, identity_key),
  constraint crm_source_records_confidence_check
    check (confidence is null or (confidence >= 0 and confidence <= 1))
);

create table if not exists public.crm_records (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  identity_key text not null,
  record_type text not null,
  status text not null default 'new',
  display_name text not null,
  owner_name text,
  property_address text,
  mailing_address text,
  phone text,
  email text,
  assigned_to text,
  tags jsonb not null default '[]'::jsonb,
  data_quality_score integer not null default 0,
  source_record_ids bigint[] not null default '{}'::bigint[],
  facts jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  last_activity_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_records_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint crm_records_tenant_id_unique
    unique (id, business_id, environment),
  constraint crm_records_scope_identity_unique
    unique (business_id, environment, identity_key),
  constraint crm_records_type_check
    check (record_type in ('property_record', 'owner_record', 'contact_record', 'probate_case_record', 'tax_delinquency_record')),
  constraint crm_records_status_check
    check (status in ('new', 'incomplete', 'clean', 'needs_skip_trace', 'marketable', 'suppressed', 'promoted', 'archived')),
  constraint crm_records_quality_score_check
    check (data_quality_score >= 0 and data_quality_score <= 100)
);

create table if not exists public.crm_record_source_memberships (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  identity_key text not null,
  record_id bigint not null,
  source_record_id bigint,
  source_system text not null,
  source_key text not null,
  list_name text,
  campaign_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint crm_record_source_memberships_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint crm_record_source_memberships_record_fkey
    foreign key (record_id, business_id, environment)
    references public.crm_records (id, business_id, environment)
    on delete cascade,
  constraint crm_record_source_memberships_source_fkey
    foreign key (source_record_id, business_id, environment)
    references public.crm_source_records (id, business_id, environment)
    on delete set null,
  constraint crm_record_source_memberships_scope_identity_unique
    unique (business_id, environment, identity_key)
);

create table if not exists public.crm_record_status_history (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  record_id bigint not null,
  from_status text,
  to_status text not null,
  actor_id text,
  actor_type text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint crm_record_status_history_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint crm_record_status_history_record_fkey
    foreign key (record_id, business_id, environment)
    references public.crm_records (id, business_id, environment)
    on delete cascade,
  constraint crm_record_status_history_from_status_check
    check (from_status is null or from_status in ('new', 'incomplete', 'clean', 'needs_skip_trace', 'marketable', 'suppressed', 'promoted', 'archived')),
  constraint crm_record_status_history_to_status_check
    check (to_status in ('new', 'incomplete', 'clean', 'needs_skip_trace', 'marketable', 'suppressed', 'promoted', 'archived'))
);

create table if not exists public.crm_record_promotions (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  record_id bigint not null,
  opportunity_id bigint not null,
  actor_id text,
  actor_type text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint crm_record_promotions_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint crm_record_promotions_record_fkey
    foreign key (record_id, business_id, environment)
    references public.crm_records (id, business_id, environment)
    on delete cascade,
  constraint crm_record_promotions_opportunity_fkey
    foreign key (opportunity_id, business_id, environment)
    references public.opportunities (id, business_id, environment)
    on delete cascade,
  constraint crm_record_promotions_scope_unique
    unique (business_id, environment, record_id, opportunity_id)
);

create index if not exists crm_source_records_scope_source_idx
  on public.crm_source_records (business_id, environment, source_system, source_key);
create index if not exists crm_records_scope_status_idx
  on public.crm_records (business_id, environment, status, updated_at desc);
create index if not exists crm_records_scope_type_idx
  on public.crm_records (business_id, environment, record_type, updated_at desc);
create index if not exists crm_record_source_memberships_record_idx
  on public.crm_record_source_memberships (business_id, environment, record_id, created_at desc);
create index if not exists crm_record_status_history_record_idx
  on public.crm_record_status_history (business_id, environment, record_id, created_at desc);
create index if not exists crm_record_promotions_record_idx
  on public.crm_record_promotions (business_id, environment, record_id, created_at desc);

alter table public.crm_source_records enable row level security;
alter table public.crm_records enable row level security;
alter table public.crm_record_source_memberships enable row level security;
alter table public.crm_record_status_history enable row level security;
alter table public.crm_record_promotions enable row level security;

drop policy if exists crm_source_records_tenant_isolation on public.crm_source_records;
create policy crm_source_records_tenant_isolation on public.crm_source_records
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop policy if exists crm_records_tenant_isolation on public.crm_records;
create policy crm_records_tenant_isolation on public.crm_records
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop policy if exists crm_record_source_memberships_tenant_isolation on public.crm_record_source_memberships;
create policy crm_record_source_memberships_tenant_isolation on public.crm_record_source_memberships
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop policy if exists crm_record_status_history_tenant_isolation on public.crm_record_status_history;
create policy crm_record_status_history_tenant_isolation on public.crm_record_status_history
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop policy if exists crm_record_promotions_tenant_isolation on public.crm_record_promotions;
create policy crm_record_promotions_tenant_isolation on public.crm_record_promotions
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop trigger if exists crm_source_records_touch_updated_at on public.crm_source_records;
create trigger crm_source_records_touch_updated_at
before update on public.crm_source_records
for each row execute function public.touch_updated_at();

drop trigger if exists crm_records_touch_updated_at on public.crm_records;
create trigger crm_records_touch_updated_at
before update on public.crm_records
for each row execute function public.touch_updated_at();

commit;
