-- Hermes control-plane migration acceptance checklist:
-- [ ] includes tables: businesses, commands, approvals, runs, tasks, artifacts, events, contacts, conversations, site_events
-- [ ] includes tenant columns: business_id, environment
-- [ ] includes idempotency_key and uniqueness for command ingestion
-- [ ] includes status fields and timestamps
-- [ ] includes explicit RLS policies keyed by business_id and environment
-- [ ] keeps site_events append-only
--
-- psql-style verification checklist:
-- verify unique index on:
-- (business_id, environment, command_type, idempotency_key)
-- verify approvals table references commands
-- verify runs table stores trigger_run_id
-- verify tasks table supports open/in_progress/completed/cancelled
-- verify contacts and conversations are tenant-scoped
-- verify site_events is append-only
-- verify RLS policies enforce business_id/environment isolation

begin;

create or replace function public.current_tenant_business_id()
returns bigint
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'business_id', '')::bigint
$$;

create or replace function public.current_tenant_environment()
returns text
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'environment', '')
$$;

create table if not exists public.businesses (
  business_id bigint generated by default as identity,
  environment text not null,
  name text not null,
  slug text not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (business_id, environment),
  unique (slug, environment),
  constraint businesses_environment_check
    check (environment in ('dev', 'staging', 'prod')),
  constraint businesses_status_check
    check (status in ('active', 'paused', 'disabled'))
);

create table if not exists public.commands (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  command_type text not null,
  source_surface text not null default 'api',
  payload jsonb not null default '{}'::jsonb,
  idempotency_key text not null,
  policy_result text not null default 'pending',
  approval_required boolean not null default false,
  status text not null default 'queued',
  requested_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commands_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint commands_status_check
    check (status in ('queued', 'approval_required', 'approved', 'rejected', 'running', 'completed', 'failed', 'cancelled')),
  constraint commands_policy_result_check
    check (policy_result in ('pending', 'safe_autonomous', 'approval_required', 'blocked'))
);

create table if not exists public.approvals (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  command_id bigint not null references public.commands (id) on delete cascade,
  approved_by text,
  approval_surface text not null default 'hermes',
  approved_payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  reason text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint approvals_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint approvals_status_check
    check (status in ('pending', 'approved', 'rejected', 'expired'))
);

create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  command_id bigint not null references public.commands (id) on delete cascade,
  parent_run_id bigint references public.runs (id) on delete set null,
  replay_source_run_id bigint references public.runs (id) on delete set null,
  replay_reason text,
  trigger_run_id text,
  status text not null default 'queued',
  error_classification text,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint runs_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint runs_status_check
    check (status in ('queued', 'running', 'completed', 'failed', 'cancelled'))
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  run_id bigint references public.runs (id) on delete cascade,
  command_id bigint references public.commands (id) on delete set null,
  task_type text not null,
  status text not null default 'open',
  priority text not null default 'normal',
  assignee text,
  details jsonb not null default '{}'::jsonb,
  due_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tasks_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint tasks_status_check
    check (status in ('open', 'in_progress', 'completed', 'cancelled')),
  constraint tasks_priority_check
    check (priority in ('low', 'normal', 'high', 'urgent'))
);

create table if not exists public.artifacts (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  run_id bigint references public.runs (id) on delete cascade,
  task_id bigint references public.tasks (id) on delete set null,
  artifact_type text not null,
  uri text,
  summary text,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint artifacts_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  command_id bigint,
  run_id bigint,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint events_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  external_contact_id text,
  name text,
  email text,
  phone text,
  channel text not null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contacts_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint contacts_status_check
    check (status in ('active', 'blocked', 'unsubscribed')),
  unique (business_id, environment, channel, external_contact_id)
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  contact_id bigint not null references public.contacts (id) on delete cascade,
  channel text not null,
  external_conversation_id text,
  subject text,
  status text not null default 'open',
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint conversations_status_check
    check (status in ('open', 'waiting', 'closed')),
  unique (business_id, environment, channel, external_conversation_id)
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  contact_id bigint,
  conversation_id bigint,
  visitor_id text,
  session_id text,
  event_name text not null,
  event_source text not null default 'website',
  idempotency_key text not null,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint site_events_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
);

create unique index if not exists commands_idempotency_unique_idx
  on public.commands (business_id, environment, command_type, idempotency_key);

create unique index if not exists site_events_idempotency_unique_idx
  on public.site_events (business_id, environment, idempotency_key);

create index if not exists businesses_status_idx
  on public.businesses (status);
create index if not exists businesses_created_at_idx
  on public.businesses (created_at desc);
create index if not exists businesses_business_id_idx
  on public.businesses (business_id);

create index if not exists commands_status_idx
  on public.commands (status);
create index if not exists commands_created_at_idx
  on public.commands (created_at desc);
create index if not exists commands_business_id_idx
  on public.commands (business_id);
create unique index if not exists commands_tenant_id_unique_idx
  on public.commands (id, business_id, environment);

create index if not exists approvals_status_idx
  on public.approvals (status);
create index if not exists approvals_created_at_idx
  on public.approvals (created_at desc);
create index if not exists approvals_business_id_idx
  on public.approvals (business_id);

create index if not exists runs_status_idx
  on public.runs (status);
create index if not exists runs_created_at_idx
  on public.runs (created_at desc);
create index if not exists runs_business_id_idx
  on public.runs (business_id);
create unique index if not exists runs_tenant_id_unique_idx
  on public.runs (id, business_id, environment);

create index if not exists tasks_status_idx
  on public.tasks (status);
create index if not exists tasks_created_at_idx
  on public.tasks (created_at desc);
create index if not exists tasks_business_id_idx
  on public.tasks (business_id);
create unique index if not exists tasks_tenant_id_unique_idx
  on public.tasks (id, business_id, environment);

create index if not exists artifacts_created_at_idx
  on public.artifacts (created_at desc);
create index if not exists artifacts_business_id_idx
  on public.artifacts (business_id);

create index if not exists events_created_at_idx
  on public.events (created_at desc);
create index if not exists events_business_id_idx
  on public.events (business_id);

create index if not exists contacts_status_idx
  on public.contacts (status);
create index if not exists contacts_created_at_idx
  on public.contacts (created_at desc);
create index if not exists contacts_business_id_idx
  on public.contacts (business_id);
create unique index if not exists contacts_tenant_id_unique_idx
  on public.contacts (id, business_id, environment);

create index if not exists conversations_status_idx
  on public.conversations (status);
create index if not exists conversations_created_at_idx
  on public.conversations (created_at desc);
create index if not exists conversations_business_id_idx
  on public.conversations (business_id);
create unique index if not exists conversations_tenant_id_unique_idx
  on public.conversations (id, business_id, environment);

create index if not exists site_events_created_at_idx
  on public.site_events (created_at desc);
create index if not exists site_events_business_id_idx
  on public.site_events (business_id);
create index if not exists site_events_visitor_id_idx
  on public.site_events (visitor_id);

alter table public.approvals
  add constraint approvals_command_tenant_fkey
  foreign key (command_id, business_id, environment)
  references public.commands (id, business_id, environment)
  on delete cascade;

alter table public.runs
  add constraint runs_command_tenant_fkey
  foreign key (command_id, business_id, environment)
  references public.commands (id, business_id, environment)
  on delete cascade;

alter table public.runs
  add constraint runs_parent_run_tenant_fkey
  foreign key (parent_run_id, business_id, environment)
  references public.runs (id, business_id, environment)
  on delete set null;

alter table public.runs
  add constraint runs_replay_source_run_tenant_fkey
  foreign key (replay_source_run_id, business_id, environment)
  references public.runs (id, business_id, environment)
  on delete set null;

alter table public.tasks
  add constraint tasks_run_tenant_fkey
  foreign key (run_id, business_id, environment)
  references public.runs (id, business_id, environment)
  on delete cascade;

alter table public.tasks
  add constraint tasks_command_tenant_fkey
  foreign key (command_id, business_id, environment)
  references public.commands (id, business_id, environment)
  on delete set null;

alter table public.artifacts
  add constraint artifacts_run_tenant_fkey
  foreign key (run_id, business_id, environment)
  references public.runs (id, business_id, environment)
  on delete cascade;

alter table public.artifacts
  add constraint artifacts_task_tenant_fkey
  foreign key (task_id, business_id, environment)
  references public.tasks (id, business_id, environment)
  on delete set null;

alter table public.events
  add constraint events_command_tenant_fkey
  foreign key (command_id, business_id, environment)
  references public.commands (id, business_id, environment);

alter table public.events
  add constraint events_run_tenant_fkey
  foreign key (run_id, business_id, environment)
  references public.runs (id, business_id, environment);

alter table public.conversations
  add constraint conversations_contact_tenant_fkey
  foreign key (contact_id, business_id, environment)
  references public.contacts (id, business_id, environment)
  on delete cascade;

alter table public.site_events
  add constraint site_events_contact_tenant_fkey
  foreign key (contact_id, business_id, environment)
  references public.contacts (id, business_id, environment);

alter table public.site_events
  add constraint site_events_conversation_tenant_fkey
  foreign key (conversation_id, business_id, environment)
  references public.conversations (id, business_id, environment);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists businesses_touch_updated_at on public.businesses;
create trigger businesses_touch_updated_at
before update on public.businesses
for each row execute function public.touch_updated_at();

drop trigger if exists commands_touch_updated_at on public.commands;
create trigger commands_touch_updated_at
before update on public.commands
for each row execute function public.touch_updated_at();

drop trigger if exists approvals_touch_updated_at on public.approvals;
create trigger approvals_touch_updated_at
before update on public.approvals
for each row execute function public.touch_updated_at();

drop trigger if exists runs_touch_updated_at on public.runs;
create trigger runs_touch_updated_at
before update on public.runs
for each row execute function public.touch_updated_at();

drop trigger if exists tasks_touch_updated_at on public.tasks;
create trigger tasks_touch_updated_at
before update on public.tasks
for each row execute function public.touch_updated_at();

drop trigger if exists contacts_touch_updated_at on public.contacts;
create trigger contacts_touch_updated_at
before update on public.contacts
for each row execute function public.touch_updated_at();

drop trigger if exists conversations_touch_updated_at on public.conversations;
create trigger conversations_touch_updated_at
before update on public.conversations
for each row execute function public.touch_updated_at();

create or replace function public.prevent_append_only_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'append-only table: % does not allow % operations', tg_table_name, tg_op;
end;
$$;

drop trigger if exists events_append_only_guard on public.events;
create trigger events_append_only_guard
before update or delete on public.events
for each row execute function public.prevent_append_only_mutation();

drop trigger if exists site_events_append_only_guard on public.site_events;
create trigger site_events_append_only_guard
before update or delete on public.site_events
for each row execute function public.prevent_append_only_mutation();

alter table public.businesses enable row level security;
alter table public.commands enable row level security;
alter table public.approvals enable row level security;
alter table public.runs enable row level security;
alter table public.tasks enable row level security;
alter table public.artifacts enable row level security;
alter table public.events enable row level security;
alter table public.contacts enable row level security;
alter table public.conversations enable row level security;
alter table public.site_events enable row level security;

create policy businesses_tenant_isolation on public.businesses
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy commands_tenant_isolation on public.commands
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy approvals_tenant_isolation on public.approvals
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy runs_tenant_isolation on public.runs
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy tasks_tenant_isolation on public.tasks
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy artifacts_tenant_isolation on public.artifacts
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy events_tenant_read_insert on public.events
for select
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy events_tenant_insert on public.events
for insert
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy contacts_tenant_isolation on public.contacts
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy conversations_tenant_isolation on public.conversations
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy site_events_tenant_read on public.site_events
for select
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy site_events_tenant_insert on public.site_events
for insert
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

comment on table public.businesses is 'Tenant registry for Hermes control plane; use service-role/trusted backend for cross-tenant administration.';
comment on table public.commands is 'State-first command records; deduped by business/environment/command_type/idempotency_key.';
comment on table public.site_events is 'Append-only site interaction events for intent and attribution analysis.';
comment on policy businesses_tenant_isolation on public.businesses is 'Trusted backend should use service-role; user JWTs must include business_id and environment claims.';

commit;
