begin;

create table if not exists public.probate_leads (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  source text not null default 'harris_county_probate',
  case_number text not null,
  file_date date,
  court_number text,
  status text,
  filing_type text not null,
  filing_subtype text,
  estate_name text,
  decedent_name text,
  keep_now boolean not null default false,
  hcad_match_status text not null default 'unmatched',
  hcad_acct text,
  owner_name text,
  mailing_address text,
  property_address text,
  contact_confidence text not null default 'none',
  lead_score numeric,
  outreach_status text,
  matched_candidate_count integer not null default 0,
  raw_payload jsonb not null default '{}'::jsonb,
  tax_delinquent boolean not null default false,
  estate_of boolean not null default false,
  pain_stack jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint probate_leads_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint probate_leads_tenant_id_unique
    unique (id, business_id, environment),
  constraint probate_leads_hcad_match_status_check
    check (hcad_match_status in ('unmatched', 'matched', 'multiple')),
  constraint probate_leads_contact_confidence_check
    check (contact_confidence in ('none', 'low', 'medium', 'high')),
  constraint probate_leads_matched_candidate_count_check
    check (matched_candidate_count >= 0)
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  source text not null default 'manual',
  lifecycle_status text not null default 'new',
  provider_name text,
  provider_lead_id text,
  provider_workspace_id text,
  identity_key text not null,
  external_key text,
  campaign_id bigint,
  list_id text,
  probate_lead_id bigint,
  email text,
  phone text,
  first_name text,
  last_name text,
  company_name text,
  company_domain text,
  website text,
  job_title text,
  mailing_address text,
  property_address text,
  probate_case_number text,
  personalization jsonb not null default '{}'::jsonb,
  custom_variables jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  score numeric,
  lt_interest_status text not null default 'neutral',
  pl_value_lead text,
  assigned_to text,
  verification_status text,
  enrichment_status text,
  upload_method text,
  is_website_visitor boolean not null default false,
  esp_code text,
  esg_code text,
  status_summary text,
  status_summary_subseq text,
  last_step text,
  last_step_variant text,
  open_count integer not null default 0,
  reply_count integer not null default 0,
  click_count integer not null default 0,
  email_opened_at timestamptz,
  email_replied_at timestamptz,
  email_clicked_at timestamptz,
  last_contacted_at timestamptz,
  last_interest_changed_at timestamptz,
  last_touched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leads_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint leads_tenant_id_unique
    unique (id, business_id, environment),
  constraint leads_probate_lead_tenant_fkey
    foreign key (probate_lead_id, business_id, environment)
    references public.probate_leads (id, business_id, environment)
    on delete set null,
  constraint leads_source_check
    check (source in ('manual', 'probate_intake', 'instantly_import', 'instantly_sync')),
  constraint leads_lifecycle_status_check
    check (lifecycle_status in ('new', 'ready', 'routed', 'active', 'suppressed', 'closed')),
  constraint leads_lt_interest_status_check
    check (
      lt_interest_status in (
        'neutral',
        'interested',
        'not_interested',
        'meeting_booked',
        'meeting_completed',
        'closed',
        'out_of_office',
        'wrong_person',
        'auto_reply',
        'unsubscribed'
      )
    ),
  constraint leads_open_count_check check (open_count >= 0),
  constraint leads_reply_count_check check (reply_count >= 0),
  constraint leads_click_count_check check (click_count >= 0)
);

create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  name text not null,
  provider_name text,
  provider_campaign_id text,
  provider_workspace_id text,
  status text not null default 'draft',
  campaign_schedule jsonb not null default '{}'::jsonb,
  pl_value text,
  is_evergreen boolean not null default false,
  sequences jsonb not null default '[]'::jsonb,
  email_gap integer,
  random_wait_max integer,
  text_only boolean not null default false,
  first_email_text_only boolean not null default false,
  email_list jsonb not null default '[]'::jsonb,
  daily_limit integer,
  stop_on_reply boolean not null default true,
  email_tag_list jsonb not null default '[]'::jsonb,
  link_tracking boolean not null default true,
  open_tracking boolean not null default true,
  stop_on_auto_reply boolean not null default true,
  daily_max_leads integer,
  prioritize_new_leads boolean not null default false,
  auto_variant_select boolean not null default false,
  match_lead_esp boolean not null default false,
  stop_for_company boolean not null default false,
  insert_unsubscribe_header boolean not null default true,
  allow_risky_contacts boolean not null default false,
  disable_bounce_protect boolean not null default false,
  limit_emails_per_company_override integer,
  cc_list jsonb not null default '[]'::jsonb,
  bcc_list jsonb not null default '[]'::jsonb,
  owned_by text,
  ai_sdr_id text,
  provider_routing_rules jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaigns_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint campaigns_tenant_id_unique
    unique (id, business_id, environment),
  constraint campaigns_status_check
    check (status in ('draft', 'active', 'paused', 'completed', 'archived'))
);

create table if not exists public.campaign_memberships (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  lead_id bigint not null,
  campaign_id bigint not null,
  provider_membership_id text,
  provider_lead_id text,
  assigned_to text,
  status text not null default 'pending',
  idempotency_key text,
  metadata jsonb not null default '{}'::jsonb,
  subscribed_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaign_memberships_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint campaign_memberships_lead_tenant_fkey
    foreign key (lead_id, business_id, environment)
    references public.leads (id, business_id, environment)
    on delete cascade,
  constraint campaign_memberships_campaign_tenant_fkey
    foreign key (campaign_id, business_id, environment)
    references public.campaigns (id, business_id, environment)
    on delete cascade,
  constraint campaign_memberships_status_check
    check (status in ('pending', 'active', 'paused', 'completed', 'suppressed', 'exited'))
);

create table if not exists public.automation_runs (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  workflow_name text not null,
  workflow_version text,
  workflow_step text,
  phase text,
  lead_id bigint,
  campaign_id bigint,
  source_event_id bigint,
  parent_run_id bigint,
  trigger_run_id text,
  provider_run_id text,
  status text not null default 'queued',
  idempotency_key text not null,
  replay_key text,
  input_payload jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  error_classification text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  constraint automation_runs_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint automation_runs_tenant_id_unique
    unique (id, business_id, environment),
  constraint automation_runs_lead_tenant_fkey
    foreign key (lead_id, business_id, environment)
    references public.leads (id, business_id, environment)
    on delete set null,
  constraint automation_runs_campaign_tenant_fkey
    foreign key (campaign_id, business_id, environment)
    references public.campaigns (id, business_id, environment)
    on delete set null,
  constraint automation_runs_parent_run_tenant_fkey
    foreign key (parent_run_id, business_id, environment)
    references public.automation_runs (id, business_id, environment)
    on delete set null,
  constraint automation_runs_status_check
    check (status in ('queued', 'in_progress', 'completed', 'failed', 'cancelled'))
);

create table if not exists public.provider_webhooks (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  provider text not null,
  event_type text not null,
  idempotency_key text not null,
  provider_event_id text,
  provider_receipt_id text,
  lead_email text,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed boolean not null default false,
  processed_at timestamptz,
  lead_event_id bigint,
  deduped boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_webhooks_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint provider_webhooks_tenant_id_unique
    unique (id, business_id, environment)
);

create table if not exists public.lead_events (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  lead_id bigint not null,
  campaign_id bigint,
  automation_run_id bigint,
  provider_name text,
  provider_event_id text,
  provider_receipt_id bigint,
  source_event_id bigint,
  event_type text not null,
  event_timestamp timestamptz not null default now(),
  received_at timestamptz not null default now(),
  idempotency_key text not null,
  payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  deduped boolean not null default false,
  created_at timestamptz not null default now(),
  constraint lead_events_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint lead_events_tenant_id_unique
    unique (id, business_id, environment),
  constraint lead_events_lead_tenant_fkey
    foreign key (lead_id, business_id, environment)
    references public.leads (id, business_id, environment)
    on delete cascade,
  constraint lead_events_campaign_tenant_fkey
    foreign key (campaign_id, business_id, environment)
    references public.campaigns (id, business_id, environment)
    on delete set null,
  constraint lead_events_automation_run_tenant_fkey
    foreign key (automation_run_id, business_id, environment)
    references public.automation_runs (id, business_id, environment)
    on delete set null,
  constraint lead_events_provider_webhook_tenant_fkey
    foreign key (provider_receipt_id, business_id, environment)
    references public.provider_webhooks (id, business_id, environment)
    on delete set null,
  constraint lead_events_source_event_tenant_fkey
    foreign key (source_event_id, business_id, environment)
    references public.lead_events (id, business_id, environment)
    on delete set null
);

create table if not exists public.suppressions (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  lead_id bigint,
  email text,
  phone text,
  campaign_id bigint,
  provider_blocklist_id text,
  scope text not null default 'global',
  scope_key text not null,
  reason text not null,
  source text not null default 'manual',
  active boolean not null default true,
  idempotency_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint suppressions_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint suppressions_lead_tenant_fkey
    foreign key (lead_id, business_id, environment)
    references public.leads (id, business_id, environment)
    on delete set null,
  constraint suppressions_campaign_tenant_fkey
    foreign key (campaign_id, business_id, environment)
    references public.campaigns (id, business_id, environment)
    on delete set null,
  constraint suppressions_scope_check
    check (scope in ('global', 'campaign')),
  constraint suppressions_source_check
    check (source in ('manual', 'provider', 'webhook', 'automation', 'import')),
  constraint suppressions_target_check
    check (lead_id is not null or email is not null or phone is not null),
  constraint suppressions_campaign_scope_check
    check (scope <> 'campaign' or campaign_id is not null)
);

create unique index if not exists probate_leads_case_unique_idx
  on public.probate_leads (business_id, environment, source, lower(case_number));
create index if not exists probate_leads_score_idx
  on public.probate_leads (business_id, environment, keep_now, lead_score desc nulls last);

create unique index if not exists leads_identity_key_unique_idx
  on public.leads (business_id, environment, identity_key);
create index if not exists leads_provider_idx
  on public.leads (business_id, environment, provider_name, provider_lead_id);
create index if not exists leads_email_idx
  on public.leads (business_id, environment, lower(email));
create index if not exists leads_campaign_idx
  on public.leads (business_id, environment, campaign_id, lifecycle_status);

create unique index if not exists campaigns_provider_unique_idx
  on public.campaigns (business_id, environment, provider_name, provider_campaign_id)
  where provider_name is not null and provider_campaign_id is not null;
create index if not exists campaigns_status_idx
  on public.campaigns (business_id, environment, status, created_at desc);

create unique index if not exists campaign_memberships_tenant_id_unique_idx
  on public.campaign_memberships (id, business_id, environment);
create unique index if not exists campaign_memberships_idempotency_unique_idx
  on public.campaign_memberships (business_id, environment, idempotency_key)
  where idempotency_key is not null;
create unique index if not exists campaign_memberships_lead_campaign_unique_idx
  on public.campaign_memberships (business_id, environment, campaign_id, lead_id);
create index if not exists campaign_memberships_status_idx
  on public.campaign_memberships (business_id, environment, status, subscribed_at desc);

create unique index if not exists automation_runs_replay_unique_idx
  on public.automation_runs (business_id, environment, workflow_name, coalesce(replay_key, idempotency_key));
create index if not exists automation_runs_lead_idx
  on public.automation_runs (business_id, environment, lead_id, created_at desc);

create unique index if not exists provider_webhooks_idempotency_unique_idx
  on public.provider_webhooks (business_id, environment, provider, idempotency_key);
create index if not exists provider_webhooks_received_idx
  on public.provider_webhooks (business_id, environment, provider, received_at desc);

create unique index if not exists lead_events_idempotency_unique_idx
  on public.lead_events (business_id, environment, idempotency_key);
create index if not exists lead_events_timeline_idx
  on public.lead_events (business_id, environment, lead_id, event_timestamp desc);
create index if not exists lead_events_campaign_idx
  on public.lead_events (business_id, environment, campaign_id, event_timestamp desc);

create unique index if not exists suppressions_scope_unique_idx
  on public.suppressions (business_id, environment, scope_key);
create unique index if not exists suppressions_tenant_id_unique_idx
  on public.suppressions (id, business_id, environment);
create unique index if not exists suppressions_idempotency_unique_idx
  on public.suppressions (business_id, environment, idempotency_key)
  where idempotency_key is not null;
create index if not exists suppressions_active_idx
  on public.suppressions (business_id, environment, active, updated_at desc);

drop trigger if exists probate_leads_touch_updated_at on public.probate_leads;
create trigger probate_leads_touch_updated_at
before update on public.probate_leads
for each row execute function public.touch_updated_at();

drop trigger if exists leads_touch_updated_at on public.leads;
create trigger leads_touch_updated_at
before update on public.leads
for each row execute function public.touch_updated_at();

drop trigger if exists campaigns_touch_updated_at on public.campaigns;
create trigger campaigns_touch_updated_at
before update on public.campaigns
for each row execute function public.touch_updated_at();

drop trigger if exists campaign_memberships_touch_updated_at on public.campaign_memberships;
create trigger campaign_memberships_touch_updated_at
before update on public.campaign_memberships
for each row execute function public.touch_updated_at();

drop trigger if exists automation_runs_touch_updated_at on public.automation_runs;
create trigger automation_runs_touch_updated_at
before update on public.automation_runs
for each row execute function public.touch_updated_at();

drop trigger if exists provider_webhooks_touch_updated_at on public.provider_webhooks;
create trigger provider_webhooks_touch_updated_at
before update on public.provider_webhooks
for each row execute function public.touch_updated_at();

drop trigger if exists suppressions_touch_updated_at on public.suppressions;
create trigger suppressions_touch_updated_at
before update on public.suppressions
for each row execute function public.touch_updated_at();

drop trigger if exists lead_events_append_only_guard on public.lead_events;
create trigger lead_events_append_only_guard
before update or delete on public.lead_events
for each row execute function public.prevent_append_only_mutation();

alter table public.probate_leads enable row level security;
alter table public.leads enable row level security;
alter table public.campaigns enable row level security;
alter table public.campaign_memberships enable row level security;
alter table public.automation_runs enable row level security;
alter table public.provider_webhooks enable row level security;
alter table public.lead_events enable row level security;
alter table public.suppressions enable row level security;

create policy probate_leads_tenant_isolation on public.probate_leads
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy leads_tenant_isolation on public.leads
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy campaigns_tenant_isolation on public.campaigns
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy campaign_memberships_tenant_isolation on public.campaign_memberships
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy automation_runs_tenant_isolation on public.automation_runs
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy provider_webhooks_tenant_isolation on public.provider_webhooks
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy lead_events_tenant_read_insert on public.lead_events
for select
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy lead_events_tenant_insert on public.lead_events
for insert
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy suppressions_tenant_isolation on public.suppressions
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

commit;
