-- Additive managed-agent/session persistence tables.
-- Keeps runtime-facing managed-agent IDs stable via text runtime_id columns.

begin;

create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  runtime_id text not null,
  business_id text not null,
  environment text not null,
  name text not null,
  description text,
  active_revision_runtime_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agents_runtime_id_unique unique (runtime_id)
);

create index if not exists agents_business_environment_idx
  on public.agents (business_id, environment);

create index if not exists agents_active_revision_runtime_id_idx
  on public.agents (active_revision_runtime_id);

create table if not exists public.agent_revisions (
  id bigint generated by default as identity primary key,
  runtime_id text not null,
  agent_runtime_id text not null,
  revision_number integer not null,
  state text not null,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  archived_at timestamptz,
  cloned_from_revision_runtime_id text,
  constraint agent_revisions_runtime_id_unique unique (runtime_id),
  constraint agent_revisions_agent_revision_number_unique unique (agent_runtime_id, revision_number),
  constraint agent_revisions_state_check
    check (state in ('draft', 'published', 'archived'))
);

create index if not exists agent_revisions_agent_runtime_id_idx
  on public.agent_revisions (agent_runtime_id);

create index if not exists agent_revisions_state_idx
  on public.agent_revisions (state);

create table if not exists public.agent_sessions (
  id bigint generated by default as identity primary key,
  runtime_id text not null,
  agent_id text not null,
  agent_revision_id text not null,
  business_id text not null,
  environment text not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_sessions_runtime_id_unique unique (runtime_id),
  constraint agent_sessions_status_check
    check (status in ('active', 'archived'))
);

create index if not exists agent_sessions_agent_revision_id_idx
  on public.agent_sessions (agent_revision_id);

create index if not exists agent_sessions_business_environment_idx
  on public.agent_sessions (business_id, environment);

create table if not exists public.agent_session_events (
  id bigint generated by default as identity primary key,
  runtime_id text not null,
  session_runtime_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint agent_session_events_runtime_id_unique unique (runtime_id)
);

create index if not exists agent_session_events_session_runtime_created_idx
  on public.agent_session_events (session_runtime_id, created_at);

commit;
