create table if not exists public.crm_record_saved_views (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  name text not null,
  slug text not null,
  filters jsonb not null default '{}'::jsonb,
  sort text not null default 'last_activity_desc',
  is_default boolean not null default false,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_record_saved_views_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint crm_record_saved_views_scope_slug_unique
    unique (business_id, environment, slug),
  constraint crm_record_saved_views_filters_check
    check (jsonb_typeof(filters) = 'object')
);

create index if not exists crm_record_saved_views_scope_default_idx
  on public.crm_record_saved_views (business_id, environment, is_default desc, name asc);

alter table public.crm_record_saved_views enable row level security;

drop policy if exists crm_record_saved_views_tenant_isolation on public.crm_record_saved_views;
create policy crm_record_saved_views_tenant_isolation on public.crm_record_saved_views
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop trigger if exists crm_record_saved_views_touch_updated_at on public.crm_record_saved_views;
create trigger crm_record_saved_views_touch_updated_at
before update on public.crm_record_saved_views
for each row execute function public.touch_updated_at();
