begin;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  contact_id bigint,
  conversation_id bigint,
  channel text not null,
  direction text not null,
  provider text,
  external_message_id text,
  subject text,
  body text not null,
  status text not null default 'queued',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint messages_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint messages_contact_tenant_fkey
    foreign key (contact_id, business_id, environment)
    references public.contacts (id, business_id, environment)
    on delete set null,
  constraint messages_conversation_tenant_fkey
    foreign key (conversation_id, business_id, environment)
    references public.conversations (id, business_id, environment)
    on delete cascade,
  constraint messages_direction_check
    check (direction in ('inbound', 'outbound')),
  constraint messages_status_check
    check (status in ('queued', 'sent', 'delivered', 'failed', 'read'))
);

create table if not exists public.booking_events (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  contact_id bigint,
  conversation_id bigint,
  event_type text not null,
  provider text not null,
  external_booking_id text,
  details jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint booking_events_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint booking_events_contact_tenant_fkey
    foreign key (contact_id, business_id, environment)
    references public.contacts (id, business_id, environment)
    on delete set null,
  constraint booking_events_conversation_tenant_fkey
    foreign key (conversation_id, business_id, environment)
    references public.conversations (id, business_id, environment)
    on delete set null,
  constraint booking_events_event_type_check
    check (event_type in ('booked', 'rescheduled', 'cancelled'))
);

create table if not exists public.sequence_enrollments (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  contact_id bigint not null,
  conversation_id bigint,
  sequence_key text not null,
  status text not null default 'active',
  enrolled_at timestamptz not null default now(),
  paused_at timestamptz,
  completed_at timestamptz,
  stopped_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sequence_enrollments_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint sequence_enrollments_contact_tenant_fkey
    foreign key (contact_id, business_id, environment)
    references public.contacts (id, business_id, environment)
    on delete cascade,
  constraint sequence_enrollments_conversation_tenant_fkey
    foreign key (conversation_id, business_id, environment)
    references public.conversations (id, business_id, environment)
    on delete set null,
  constraint sequence_enrollments_status_check
    check (status in ('active', 'paused', 'completed', 'stopped'))
);

create index if not exists messages_contact_id_created_at_idx
  on public.messages (business_id, environment, contact_id, created_at desc);
create index if not exists messages_conversation_id_created_at_idx
  on public.messages (business_id, environment, conversation_id, created_at desc);

create index if not exists booking_events_contact_id_occurred_at_idx
  on public.booking_events (business_id, environment, contact_id, occurred_at desc);
create index if not exists booking_events_conversation_id_occurred_at_idx
  on public.booking_events (business_id, environment, conversation_id, occurred_at desc);

create unique index if not exists sequence_enrollments_active_unique_idx
  on public.sequence_enrollments (business_id, environment, contact_id, sequence_key)
  where status = 'active';
create index if not exists sequence_enrollments_status_idx
  on public.sequence_enrollments (business_id, environment, status, enrolled_at desc);

drop trigger if exists messages_touch_updated_at on public.messages;
create trigger messages_touch_updated_at
before update on public.messages
for each row execute function public.touch_updated_at();

drop trigger if exists sequence_enrollments_touch_updated_at on public.sequence_enrollments;
create trigger sequence_enrollments_touch_updated_at
before update on public.sequence_enrollments
for each row execute function public.touch_updated_at();

alter table public.messages enable row level security;
alter table public.booking_events enable row level security;
alter table public.sequence_enrollments enable row level security;

create policy messages_tenant_isolation on public.messages
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy booking_events_tenant_read_insert on public.booking_events
for select
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy booking_events_tenant_insert on public.booking_events
for insert
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

create policy sequence_enrollments_tenant_isolation on public.sequence_enrollments
for all
using (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
)
with check (
  business_id = public.current_tenant_business_id()
  and environment = public.current_tenant_environment()
);

commit;
