create table if not exists public.provider_object_links (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  provider text not null,
  provider_object_type text not null,
  provider_object_id text not null,
  ares_object_type text not null,
  ares_object_id text not null,
  link_status text not null default 'active',
  sync_hash text,
  last_synced_at timestamptz,
  last_seen_at timestamptz,
  conflict_reason text,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_object_links_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint provider_object_links_status_check
    check (link_status in ('active', 'stale', 'conflict', 'archived')),
  constraint provider_object_links_raw_payload_check
    check (jsonb_typeof(raw_payload) = 'object'),
  constraint provider_object_links_identity_lower_check
    check (
      provider = lower(provider) and
      provider_object_type = lower(provider_object_type) and
      ares_object_type = lower(ares_object_type)
    ),
  constraint provider_object_links_provider_object_unique
    unique (business_id, environment, provider, provider_object_type, provider_object_id),
  constraint provider_object_links_ares_provider_type_unique
    unique (business_id, environment, provider, ares_object_type, ares_object_id, provider_object_type)
);

create index if not exists provider_object_links_ares_lookup_idx
  on public.provider_object_links (business_id, environment, provider, ares_object_type, ares_object_id, provider_object_type);

create index if not exists provider_object_links_provider_lookup_idx
  on public.provider_object_links (business_id, environment, provider, provider_object_type, provider_object_id);

create index if not exists provider_object_links_status_seen_idx
  on public.provider_object_links (business_id, environment, provider, link_status, last_seen_at desc);

create table if not exists public.provider_sync_cursors (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  provider text not null,
  sync_name text not null,
  cursor_value text,
  cursor_payload jsonb not null default '{}'::jsonb,
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_sync_cursors_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint provider_sync_cursors_cursor_payload_check
    check (jsonb_typeof(cursor_payload) = 'object'),
  constraint provider_sync_cursors_provider_lower_check
    check (provider = lower(provider)),
  constraint provider_sync_cursors_tenant_provider_sync_unique
    unique (business_id, environment, provider, sync_name)
);

create index if not exists provider_sync_cursors_scope_idx
  on public.provider_sync_cursors (business_id, environment, provider, sync_name);

create table if not exists public.provider_sync_runs (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  provider text not null,
  sync_name text not null,
  direction text not null default 'ares_to_provider',
  status text not null default 'queued',
  idempotency_key text not null,
  cursor_before text,
  cursor_after text,
  started_at timestamptz,
  completed_at timestamptz,
  scanned_count integer not null default 0,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  conflict_count integer not null default 0,
  error_count integer not null default 0,
  input_payload jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  error_message text,
  command_id bigint,
  run_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_sync_runs_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint provider_sync_runs_command_fkey
    foreign key (command_id)
    references public.commands (id)
    on delete set null,
  constraint provider_sync_runs_run_fkey
    foreign key (run_id)
    references public.runs (id)
    on delete set null,
  constraint provider_sync_runs_direction_check
    check (direction in ('ares_to_provider', 'provider_to_ares', 'bidirectional', 'dry_run')),
  constraint provider_sync_runs_status_check
    check (status in ('queued', 'in_progress', 'completed', 'failed', 'cancelled')),
  constraint provider_sync_runs_counts_check
    check (
      scanned_count >= 0 and created_count >= 0 and updated_count >= 0 and
      skipped_count >= 0 and conflict_count >= 0 and error_count >= 0
    ),
  constraint provider_sync_runs_input_payload_check
    check (jsonb_typeof(input_payload) = 'object'),
  constraint provider_sync_runs_output_payload_check
    check (jsonb_typeof(output_payload) = 'object'),
  constraint provider_sync_runs_provider_lower_check
    check (provider = lower(provider)),
  constraint provider_sync_runs_tenant_provider_sync_idempotency_unique
    unique (business_id, environment, provider, sync_name, idempotency_key)
);

create index if not exists provider_sync_runs_scope_started_idx
  on public.provider_sync_runs (business_id, environment, provider, sync_name, started_at desc, id desc);

create index if not exists provider_sync_runs_status_idx
  on public.provider_sync_runs (business_id, environment, status, created_at desc);

alter table public.provider_object_links enable row level security;
alter table public.provider_sync_cursors enable row level security;
alter table public.provider_sync_runs enable row level security;

drop policy if exists provider_object_links_tenant_isolation on public.provider_object_links;
create policy provider_object_links_tenant_isolation on public.provider_object_links
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop policy if exists provider_sync_cursors_tenant_isolation on public.provider_sync_cursors;
create policy provider_sync_cursors_tenant_isolation on public.provider_sync_cursors
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop policy if exists provider_sync_runs_tenant_isolation on public.provider_sync_runs;
create policy provider_sync_runs_tenant_isolation on public.provider_sync_runs
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

drop trigger if exists provider_object_links_touch_updated_at on public.provider_object_links;
create trigger provider_object_links_touch_updated_at
before update on public.provider_object_links
for each row execute function public.touch_updated_at();

drop trigger if exists provider_sync_cursors_touch_updated_at on public.provider_sync_cursors;
create trigger provider_sync_cursors_touch_updated_at
before update on public.provider_sync_cursors
for each row execute function public.touch_updated_at();

drop trigger if exists provider_sync_runs_touch_updated_at on public.provider_sync_runs;
create trigger provider_sync_runs_touch_updated_at
before update on public.provider_sync_runs
for each row execute function public.touch_updated_at();
