begin;

create table if not exists public.sms_agent_jobs (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  provider_webhook_id bigint,
  message_id bigint,
  conversation_id bigint,
  contact_id bigint,
  from_number text not null,
  to_number text not null,
  payload_hash text,
  status text not null default 'pending',
  attempt_count integer not null default 0,
  locked_until timestamptz,
  decision_id bigint,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sms_agent_jobs_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint sms_agent_jobs_id_tenant_unique unique (id, business_id, environment),
  constraint sms_agent_jobs_status_check
    check (status in ('pending', 'processing', 'completed', 'blocked', 'failed_retryable', 'failed_terminal'))
);

create table if not exists public.sms_agent_decisions (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  job_id bigint not null,
  message_id bigint,
  conversation_id bigint,
  contact_id bigint,
  intent text not null,
  source_lane text not null,
  temperature text not null,
  urgency text not null,
  action text not null,
  suggested_body text,
  confidence numeric not null default 0,
  policy_reason text not null,
  prompt_version text not null,
  provider_kind text,
  model text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint sms_agent_decisions_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade,
  constraint sms_agent_decisions_id_tenant_unique unique (id, business_id, environment),
  constraint sms_agent_decisions_job_fkey
    foreign key (job_id, business_id, environment)
    references public.sms_agent_jobs(id, business_id, environment)
    on delete cascade,
  constraint sms_agent_decisions_confidence_check check (confidence >= 0 and confidence <= 1)
);

alter table public.sms_agent_jobs
  add constraint sms_agent_jobs_decision_fkey
  foreign key (decision_id, business_id, environment)
  references public.sms_agent_decisions(id, business_id, environment)
  on delete set null (decision_id);

create table if not exists public.sms_agent_eval_labels (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  decision_id bigint not null references public.sms_agent_decisions(id) on delete cascade,
  label text not null,
  reviewer text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint sms_agent_eval_labels_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade
);

create table if not exists public.sms_agent_archives (
  id bigint generated by default as identity primary key,
  business_id bigint not null,
  environment text not null,
  decision_id bigint references public.sms_agent_decisions(id) on delete set null,
  archive_uri text not null,
  content_sha256 text not null,
  redacted boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint sms_agent_archives_business_fkey
    foreign key (business_id, environment)
    references public.businesses (business_id, environment)
    on delete cascade
);

create unique index if not exists sms_agent_jobs_webhook_message_unique_idx
  on public.sms_agent_jobs (business_id, environment, coalesce(provider_webhook_id, 0), coalesce(message_id, 0), coalesce(payload_hash, ''))
  where provider_webhook_id is not null or message_id is not null or payload_hash is not null;
create index if not exists sms_agent_jobs_pending_idx
  on public.sms_agent_jobs (business_id, environment, status, locked_until, created_at);
create index if not exists sms_agent_decisions_job_idx
  on public.sms_agent_decisions (business_id, environment, job_id, created_at desc);
create unique index if not exists sms_agent_decisions_operator_send_request_unique_idx
  on public.sms_agent_decisions (business_id, environment, (metadata->>'parent_decision_id'))
  where action = 'operator_send_requested' and metadata->>'parent_decision_id' is not null;
create index if not exists sms_agent_eval_labels_decision_idx
  on public.sms_agent_eval_labels (business_id, environment, decision_id, created_at desc);

drop trigger if exists sms_agent_jobs_touch_updated_at on public.sms_agent_jobs;
create trigger sms_agent_jobs_touch_updated_at
before update on public.sms_agent_jobs
for each row execute function public.touch_updated_at();

alter table public.sms_agent_jobs enable row level security;
alter table public.sms_agent_decisions enable row level security;
alter table public.sms_agent_eval_labels enable row level security;
alter table public.sms_agent_archives enable row level security;

create policy sms_agent_jobs_tenant_isolation on public.sms_agent_jobs
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

create policy sms_agent_decisions_tenant_isolation on public.sms_agent_decisions
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

create policy sms_agent_eval_labels_tenant_isolation on public.sms_agent_eval_labels
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

create policy sms_agent_archives_tenant_isolation on public.sms_agent_archives
for all
using (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment())
with check (business_id = public.current_tenant_business_id() and environment = public.current_tenant_environment());

commit;
